chore: Add liveness probe to redis server pod

diff --git a/prototypes/gpu_workload_v1/redis_producer/charts/server/templates/server-pod.yaml b/prototypes/gpu_workload_v1/redis_producer/charts/server/templates/server-pod.yaml
--- a/prototypes/gpu_workload_v1/redis_producer/charts/server/templates/server-pod.yaml
+++ b/prototypes/gpu_workload_v1/redis_producer/charts/server/templates/server-pod.yaml
@@ -14,18 +14,30 @@ spec:
           value: "true"
       ports:
         - containerPort: 6379
-      # livenessProbe:
-      #   httpGet:
-      #     path: ping
-      #     port: 6379
-      #   initialDelaySeconds: 15
-      #   timeoutSeconds: 2
-      #   periodSeconds: 5
-      #   failureThreshold: 1
-      # readinessProbe:
-      #   httpGet:
-      #     path: ping
-      #     port: 6379
-      #   initialDelaySeconds: 3
-      #   periodSeconds: 5
-      #   failureThreshold: 1
+      livenessProbe:
+          exec:
+            command:
+            - sh
+            - -c
+            - |            
+                #!/usr/bin/env bash -e
+                #export REDISCLI_AUTH="$REDIS_PASSWORD"
+
+                set_response=$(
+                  redis-cli set liveness_test_key "SUCCESS"
+                )
+
+                del_response=$(
+                    redis-cli del liveness_test_key
+                )
+
+                response=$(
+                  redis-cli get liveness_test_key
+                )
+
+                if [ "$response" != "SUCCESS" ] ; then
+                  echo "Unable to get keys, something is wrong"
+                  exit 1
+                fi               
+          initialDelaySeconds: 5
+          periodSeconds: 5
